### ISSUE TITLE
Empty Value option does not seem to  work for CSVWriter when all the fileds are not quoted.

### ISSUE THREAD

**Issue by sureshthalamati** [uniVocity/univocity-parsers#123]
While working on a Spark Jira to differentiate between empty strings  and null value in Spark CSV library for reading and writing  I ran into the following  problem. (https://issues.apache.org/jira/browse/SPARK-15125). 

// if the value is not null, but is empty (e.g. ""), the writer will can be configured to
// print some default representation for a non-null/empty value
settings.setEmptyValue("!");

Empty Value option does not seem to  work when all the fields are NOT quoted. nullValue is written for empty values also when 

It works fine on reading , but on write empty value is written only when quotes are enabled for all the fields. I am not sure what is the rational behind this choice , it would be nice this option can be enhanced to write emptyValue when quotes are not enabled also, especially when user sets the empty value. 

Here is what I noticed when I debugged the code , there is specific check if elements are quoted are not before writing empty value.

https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/csv/CsvWriter.java
processRow()

//skipped all whitespaces and wrote nothing
			if (appender.length() == originalLength) {
				if (isElementQuoted) {
					if (nextElement == null) {
						append(false, nullValue);
					} else {
						append(true, emptyValue);
					}
				} else {
					append(false, nullValue);
				}
			}

--

If there is any way to work around this issue,  please let know.  Thank you very much.

**Comment by jbax** [comment]
Thanks for reporting the issue! I've fixed it and released a 2.2.3-SNAPSHOT build that you can used.

Thank you for using our parsers!

**Comment by sureshthalamati** [comment]
Thank you very much for fixing this issue.  I tried the fix 2.2.3 release , it does write  unquoted empty value , instead of null value.   I am running into a minor problem though.  As part of the write I want to write quoted empty string for empty string values in the data frame.  I can not get this to work , either it write empty field or escapes quote chars if I set quoutes ("") set using setEmptyValue("\"\"") call.   I want to write quoted empty string (""), so that CSV reader can read  empty strings correctly.  

Example :

ROW:   1, “”, 3, null

Expected written data :  1,””,3,

I tried with the following settings.

1)

format.setQuoteEscape(‘\\')
writerSettings.setNullValue(null)
 writerSettings.setEmptyValue(“\”\””)   // java escape

Writes it as :

1,,3,

2)

format.setQuoteEscape(‘\\')
writerSettings.setNullValue(null)
 writerSettings.setEmptyValue(“\”\””)   // java escape

Row  gets writes as :

1,”\”\”

It would be nice if there is an option to write empty strings as  quoted empty strings.   

Any suggestion to solve this problem ?

**Comment by jbax** [comment]
Fixed in [this commit](https://github.com/uniVocity/univocity-parsers/commit/f2976b000f2d82d29369223e1279c26790d733bd). A build for version 2.3.0-SNAPSHOT has been generated to include this fix.

Thanks for pointing out this issue.

**Comment by sureshthalamati** [comment]
Thank you very much for  quickly fixing the issue. I tested the snapshot build , It works when quote escaping enabled is  set to false.  But when quote escaping is enabled, quotes  are  still getting escaped.  By default , spark sets quote escaping enabled to true. I am still running into problem of not able to write quoted empty strings for empty string value. 

 writerSettings.setEmptyValue(“\”\””) 
writerSettings.setQuoteEscapingEnabled(true)
 
1, "", "abcd"  is getting  written  as :   1,"\"\"",abcd

**Comment by sureshthalamati** [comment]
Thank you very much for quickly fixing the issues, it fixed the issues.   What is the release time frame for 2.3 ?

**Comment by jbax** [comment]
A few minutes ago :) - sorry for replying just now, I found your question after reviewing the issues fixed to write the release notes.
