### ISSUE TITLE
@Validate annotation is ignored in some cases

### ISSUE THREAD

**Issue by PeRane** [uniVocity/univocity-parsers#266]
I'm using BeanProcessor on a Java Bean that have annotated some fields using @Validate.
Because in class DefaultConversionProcessor, you are checking the length of the validation index array instead of the values, validation will be stopped if rowIndex == validatedIndexes.length

**Comment by jbax** [comment]
Thank you for reporting the bug. I've fixed it and released a 2.7.4-SNAPSHOT build which you can use to test before I release the "final" 2.7.4 build.

To learn about getting a snapshot build, have a look here:
https://www.univocity.com/pages/univocity_parsers_download#snapshot-releases

Thank you for using our parsers!

**Comment by jbax** [comment]
Version 2.7.4 released.
Thanks again

**Comment by PeRane** [comment]
Sorry, but there is still an issue with the index.

In DefaultConversionProcessor, line 146:

`Object value = index < objectRow.length ? objectRow[i] : null;`

Should be:

`Object value = index < objectRow.length ? objectRow[index] : null;`

Thanks a lot

**Comment by jbax** [comment]
Thanks! Looking for a paper bag to bury my head in. 

Fixed on 2.7.5.
