### ISSUE TITLE
Headers being extracted when not expected, and this is leading to memory leak

### ISSUE THREAD

**Issue by ashutoshmimani** [uniVocity/univocity-parsers#326]
I have a byte array that contains a single tsv record only (no header). I wrap this in a ByteArrayInputStream and begin parsing.

parser settings:
headerExtractionEnabled: false
headers: null

The record is still parsed as a header in ParserOutput and all the fields are added to the StringCache of NormalizedString. As I read more such byte arrays, all these fields are added to the cache. This seems like a memory leak.

I get around this currently by providing a dummy headers array in parser settings. If this is the intended way to use, then perhaps documentation should be updated. And even better if we can enforce that either headers or headerExtractionEnabled be set - and throw an exception if this isn't satisfied.

IMO if headerExtractionEnabled is false, ParserOutput should not assume first record read is a header. (I haven't tried it yet, but maybe in ParserOutput, initializeHeaders() should not be called from rowParsed() if headerExtractionEnabled is false)

Another nice to have is a way to disable the NormalizedString cache entirely. If the parser is merely used to load data and create POJOs, then once all the data parsed, and the parser is garbage collected, we shouldn't have header strings taking up memory. I understand the purpose is to store headers only, so it may not take a whole lot of memory. Regardless, it is still technically a memory leak and it should be avoided. If NormalizedString/StringCache has to be there for some performance reasons, then a possible fix is to make each each parser have its own NormalizeString/StringCache instance instead of sharing that across all parser instances.

**Comment by jbax** [comment]
Majes sense, I'll fix that today.

**Comment by jbax** [comment]
Fixed. NormalizedString now has a `getCache` method you can use to configure how many entries the cache should have/clear or do whatever you want. By default it will store up to 16384 entries and then will discard everything to start anew if more room is needed.

I'll try to have a 2.8.2 release ready today. Thank you for reporting this bug and for using our parsers!

**Comment by ashutoshmimani** [comment]
@jbax thanks for taking this up so quickly! I still have a few questions/concerns though -
1. the getCache method added to NormalizedString isn't static. how does one access it?
2. no change made to ParserOutput. if headerExtractionEnabled is false, it will still call initializeHeaders() from rowParsed(). is this expected?
3. limiting size of string cache seems like a stop-gap measure. it is limiting the scope of the issue, but not really fixing it. long term i hope you would consider making NormalizedString not be shared across parsers, so garbage collection can cleanup the string cache. would love to understand if there is a benefit of making it be shared across parsers.

**Comment by jbax** [comment]
1. Accidents happen. It should be static otherwise you'd have to use a
NormalizedString instance

2. That is expected. The parser uses the first row for internal
initialization.

3. The idea here is pretty much the same why java has an internal string
pool: optimize frequent access to recently generated strings. Keeping a
small pool of NormalizedString in memory is not a big deal and making it
parser dependent would be over engineering the issue. It would make the
code more complex as you'd have to pass references around lots of classes
and make every cache instance the central source of NormalizedString which
goes against the intent of this class. I want to use NormalizedString as
drop in replacement for regular strings when needed, and not care about
implementation details.

Hope this addresses your questions

Thanks!

**Comment by ashutoshmimani** [comment]
1. Will a fix be released after making the method static?
2. If headerExtractionEnabled is false, the parser shouldn't be using the first row as a header. Or is the flag supposed to mean something else?
3. Thanks for the explanation around use of NormalizedString. I'm not sure I agree with it, but perhaps you have different use cases I haven't encountered or thought of.

**Comment by jbax** [comment]
1. Yes and I already fixed it. Will be on version 2.8.3

2. That is an internal implementation detail. Don't worry about it. At a
minimum the parser needs to use something to initialize index based field
selections and other stuff that I can't remember now but there are some few
cases were these values matter. You can try changing the code and running
the test cases to see what blows up.

3. There are. This is also used in some other libraries we built to handle
column names in database tables, among other things.
